import type { Metadata } from "next";
import { ReactQueryProvider, ReactReduxProvider, ReactHotToastProvider } from '@/providers';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactHotToastProvider>
          <ReactQueryProvider>
            <ReactReduxProvider>
              {children}
            </ReactReduxProvider>
          </ReactQueryProvider>
        </ReactHotToastProvider>
      </body>
    </html>
  );
}
